window.BRAND_DATA = [
  {
    id: "garmin",
    name: "Garmin",
    initials: "G",
    category: "Електроніка",
    country: "США",
    countryCode: "US",
    type: "Сайт виробника",
    status: "verified",
    site: "garmin.com",
    url: "https://www.garmin.com/",
    checked: "25.07.2026",
    note: "Глобальний сайт виробника навігаційної електроніки та спортивних пристроїв."
  },
  {
    id: "thalgo",
    name: "Thalgo",
    initials: "T",
    category: "Косметика",
    country: "Франція",
    countryCode: "FR",
    type: "Сайт виробника",
    status: "verified",
    site: "thalgo.com",
    url: "https://www.thalgo.com/",
    checked: "24.07.2026",
    note: "Глобальний сайт професійної морської косметики."
  },
  {
    id: "bosch",
    name: "Bosch",
    initials: "B",
    category: "Побутова техніка",
    country: "Німеччина",
    countryCode: "DE",
    type: "Регіональний сайт",
    status: "verified",
    site: "bosch.com",
    url: "https://www.bosch.com/",
    checked: "23.07.2026",
    note: "Корпоративний сайт групи Bosch із переходами до регіональних напрямів."
  },
  {
    id: "lego",
    name: "LEGO",
    initials: "L",
    category: "Дитячі товари",
    country: "Данія",
    countryCode: "DK",
    type: "Сайт виробника",
    status: "verified",
    site: "lego.com",
    url: "https://www.lego.com/",
    checked: "22.07.2026",
    note: "Глобальний сайт виробника конструкторів."
  },
  {
    id: "samsung",
    name: "Samsung",
    initials: "S",
    category: "Електроніка",
    country: "Південна Корея",
    countryCode: "KR",
    type: "Регіональний сайт",
    status: "verified",
    site: "samsung.com",
    url: "https://www.samsung.com/",
    checked: "21.07.2026",
    note: "Глобальний портал із локальними версіями для різних країн."
  },
  {
    id: "ikea",
    name: "IKEA",
    initials: "I",
    category: "Товари для дому",
    country: "Швеція",
    countryCode: "SE",
    type: "Регіональний сайт",
    status: "verified",
    site: "ikea.com",
    url: "https://www.ikea.com/",
    checked: "20.07.2026",
    note: "Офіційний глобальний портал бренду з регіональними магазинами."
  },
  {
    id: "adidas",
    name: "adidas",
    initials: "A",
    category: "Одяг і взуття",
    country: "Німеччина",
    countryCode: "DE",
    type: "Сайт виробника",
    status: "verified",
    site: "adidas.com",
    url: "https://www.adidas.com/",
    checked: "18.07.2026",
    note: "Офіційний глобальний сайт спортивного бренду."
  },
  {
    id: "patagonia",
    name: "Patagonia",
    initials: "P",
    category: "Спорт і туризм",
    country: "США",
    countryCode: "US",
    type: "Сайт виробника",
    status: "verified",
    site: "patagonia.com",
    url: "https://www.patagonia.com/",
    checked: "17.07.2026",
    note: "Офіційний сайт виробника одягу та спорядження для активного відпочинку."
  },
  {
    id: "dyson",
    name: "Dyson",
    initials: "D",
    category: "Побутова техніка",
    country: "Велика Британія",
    countryCode: "GB",
    type: "Сайт виробника",
    status: "verified",
    site: "dyson.com",
    url: "https://www.dyson.com/",
    checked: "16.07.2026",
    note: "Офіційний сайт технологічної компанії Dyson."
  },
  {
    id: "apple",
    name: "Apple",
    initials: "A",
    category: "Електроніка",
    country: "США",
    countryCode: "US",
    type: "Сайт виробника",
    status: "verified",
    site: "apple.com",
    url: "https://www.apple.com/",
    checked: "15.07.2026",
    note: "Офіційний глобальний сайт Apple."
  },
  {
    id: "zo-skin-health",
    name: "ZO Skin Health",
    initials: "ZO",
    category: "Косметика",
    country: "США",
    countryCode: "US",
    type: "Сайт виробника",
    status: "review",
    site: "zoskinhealth.com",
    url: "https://zoskinhealth.com/",
    checked: "12.06.2026",
    note: "Запис потребує планової повторної перевірки регіональних сторінок."
  },
  {
    id: "example-distributor",
    name: "Приклад дистриб’ютора",
    initials: "ПД",
    category: "Косметика",
    country: "Україна",
    countryCode: "UA",
    type: "Заявлений дистриб’ютор",
    status: "unconfirmed",
    site: "example.ua",
    url: "#",
    checked: "10.07.2026",
    note: "Демонстраційний запис: незалежне підтвердження статусу не знайдено."
  }
];
