window.BRAND_DATA = [
  {
    "id": "apple",
    "name": "Apple",
    "initials": "A",
    "category": "Технології / Електроніка",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "apple.com",
    "url": "https://www.apple.com",
    "checked": "28.07.2026",
    "note": "Смартфони iPhone, ПК Mac, планшети iPad, ОС iOS Рік заснування: 1976.",
    "year": "1976"
  },
  {
    "id": "microsoft",
    "name": "Microsoft",
    "initials": "M",
    "category": "ПО / Хмарні сервіси",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "microsoft.com",
    "url": "https://www.microsoft.com",
    "checked": "28.07.2026",
    "note": "Операційна система Windows, MS Office, Azure, Xbox Рік заснування: 1975.",
    "year": "1975"
  },
  {
    "id": "google-alphabet",
    "name": "Google (Alphabet)",
    "initials": "G",
    "category": "Інтернет-сервіси / ПО",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "google.com",
    "url": "https://www.google.com",
    "checked": "28.07.2026",
    "note": "Пошукова система, Android, YouTube, Google Cloud Рік заснування: 1998.",
    "year": "1998"
  },
  {
    "id": "samsung",
    "name": "Samsung",
    "initials": "S",
    "category": "Електроніка / Технології",
    "country": "Південна Корея",
    "countryCode": "KR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "samsung.com",
    "url": "https://www.samsung.com",
    "checked": "28.07.2026",
    "note": "Смартфони Galaxy, побутова техніка, дисплеї Рік заснування: 1938.",
    "year": "1938"
  },
  {
    "id": "sony",
    "name": "Sony",
    "initials": "S",
    "category": "Електроніка / Розваги",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "sony.com",
    "url": "https://www.sony.com",
    "checked": "28.07.2026",
    "note": "Ігрові консолі PlayStation, аудіо, фотокамери Рік заснування: 1946.",
    "year": "1946"
  },
  {
    "id": "nvidia",
    "name": "NVIDIA",
    "initials": "NV",
    "category": "Напівпровідники / AI",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "nvidia.com",
    "url": "https://www.nvidia.com",
    "checked": "28.07.2026",
    "note": "Графічні процесори GeForce, чіпи для штучного інтелекту Рік заснування: 1993.",
    "year": "1993"
  },
  {
    "id": "intel",
    "name": "Intel",
    "initials": "I",
    "category": "Напівпровідники",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "intel.com",
    "url": "https://www.intel.com",
    "checked": "28.07.2026",
    "note": "Мікропроцесори Core, Xeon, обладнання для ПК Рік заснування: 1968.",
    "year": "1968"
  },
  {
    "id": "dell-technologies",
    "name": "Dell Technologies",
    "initials": "DT",
    "category": "Комп'ютерна техніка",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "dell.com",
    "url": "https://www.dell.com",
    "checked": "28.07.2026",
    "note": "Ноутбуки, сервери, монітори, корпоративні IT-рішення Рік заснування: 1984.",
    "year": "1984"
  },
  {
    "id": "lg-electronics",
    "name": "LG Electronics",
    "initials": "LE",
    "category": "Побутова техніка / Електроніка",
    "country": "Південна Корея",
    "countryCode": "KR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "lg.com",
    "url": "https://www.lg.com",
    "checked": "28.07.2026",
    "note": "Телевізори OLED, холодильники, пральні машини Рік заснування: 1958.",
    "year": "1958"
  },
  {
    "id": "asus",
    "name": "ASUS",
    "initials": "AS",
    "category": "Комп'ютерна техніка",
    "country": "Тайвань",
    "countryCode": "TW",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "asus.com",
    "url": "https://www.asus.com",
    "checked": "28.07.2026",
    "note": "Ноутбуки ROG/ZenBook, материнські плати, монітори Рік заснування: 1989.",
    "year": "1989"
  },
  {
    "id": "toyota",
    "name": "Toyota",
    "initials": "T",
    "category": "Автомобілебудування",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "toyota.com",
    "url": "https://www.toyota.com",
    "checked": "28.07.2026",
    "note": "Легкові автомобілі, гібриди, позашляховики Рік заснування: 1937.",
    "year": "1937"
  },
  {
    "id": "volkswagen",
    "name": "Volkswagen",
    "initials": "V",
    "category": "Автомобілебудування",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "volkswagen.com",
    "url": "https://www.volkswagen.com",
    "checked": "28.07.2026",
    "note": "Автомобілі VW, групи Audi, Porsche, Skoda Рік заснування: 1937.",
    "year": "1937"
  },
  {
    "id": "bmw",
    "name": "BMW",
    "initials": "BM",
    "category": "Преміум-автомобілі",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "bmw.com",
    "url": "https://www.bmw.com",
    "checked": "28.07.2026",
    "note": "Автомобілі BMW, мотоцикли BMW Motorrad, Rolls-Royce Рік заснування: 1916.",
    "year": "1916"
  },
  {
    "id": "mercedes-benz",
    "name": "Mercedes-Benz",
    "initials": "MB",
    "category": "Преміум-автомобілі",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "mercedes-benz.com",
    "url": "https://www.mercedes-benz.com",
    "checked": "28.07.2026",
    "note": "Легкові автомобілі, люкс-сегмент, вантажівки Рік заснування: 1926.",
    "year": "1926"
  },
  {
    "id": "tesla",
    "name": "Tesla",
    "initials": "T",
    "category": "Електромобілі / Енергетика",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "tesla.com",
    "url": "https://www.tesla.com",
    "checked": "28.07.2026",
    "note": "Електромобілі Model S/3/X/Y, акумулятори, сонячні панелі Рік заснування: 2003.",
    "year": "2003"
  },
  {
    "id": "ford",
    "name": "Ford",
    "initials": "F",
    "category": "Автомобілебудування",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "ford.com",
    "url": "https://www.ford.com",
    "checked": "28.07.2026",
    "note": "Легкові автомобілі, пікапи F-150, позашляховики Рік заснування: 1903.",
    "year": "1903"
  },
  {
    "id": "honda",
    "name": "Honda",
    "initials": "H",
    "category": "Автомобілі / Мототехніка",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "global.honda",
    "url": "https://global.honda",
    "checked": "28.07.2026",
    "note": "Автомобілі, мотоцикли, силова техніка Рік заснування: 1948.",
    "year": "1948"
  },
  {
    "id": "hyundai",
    "name": "Hyundai",
    "initials": "H",
    "category": "Автомобілебудування",
    "country": "Південна Корея",
    "countryCode": "KR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "hyundai.com",
    "url": "https://www.hyundai.com",
    "checked": "28.07.2026",
    "note": "Легкові автомобілі, електромобілі серії Ioniq Рік заснування: 1967.",
    "year": "1967"
  },
  {
    "id": "porsche",
    "name": "Porsche",
    "initials": "P",
    "category": "Спортивні автомобілі",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "porsche.com",
    "url": "https://www.porsche.com",
    "checked": "28.07.2026",
    "note": "Спортивні автомобілі 911, Cayenne, Taycan Рік заснування: 1931.",
    "year": "1931"
  },
  {
    "id": "ferrari",
    "name": "Ferrari",
    "initials": "F",
    "category": "Суперкари / Автоспорт",
    "country": "Італія",
    "countryCode": "IT",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "ferrari.com",
    "url": "https://www.ferrari.com",
    "checked": "28.07.2026",
    "note": "Преміальні суперкари, команда Formula 1 Рік заснування: 1939.",
    "year": "1939"
  },
  {
    "id": "nike",
    "name": "Nike",
    "initials": "N",
    "category": "Спортивне взуття та одяг",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "nike.com",
    "url": "https://www.nike.com",
    "checked": "28.07.2026",
    "note": "Кросівки Air Max/Jordan, спортивне екіпірування Рік заснування: 1964.",
    "year": "1964"
  },
  {
    "id": "adidas",
    "name": "Adidas",
    "initials": "A",
    "category": "Спортивний одяг та взуття",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "adidas.com",
    "url": "https://www.adidas.com",
    "checked": "28.07.2026",
    "note": "Кросівки Originals/Boost, спортивне спорядження Рік заснування: 1949.",
    "year": "1949"
  },
  {
    "id": "louis-vuitton-lvmh",
    "name": "Louis Vuitton (LVMH)",
    "initials": "LV",
    "category": "Люкс / Мода",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "louisvuitton.com",
    "url": "https://www.louisvuitton.com",
    "checked": "28.07.2026",
    "note": "Сумки, аксесуари, одяг високої моди, предмети розкоші Рік заснування: 1854.",
    "year": "1854"
  },
  {
    "id": "gucci",
    "name": "Gucci",
    "initials": "G",
    "category": "Люкс / Мода",
    "country": "Італія",
    "countryCode": "IT",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "gucci.com",
    "url": "https://www.gucci.com",
    "checked": "28.07.2026",
    "note": "Преміум одяг, шкіряні вироби, парфумерія Рік заснування: 1921.",
    "year": "1921"
  },
  {
    "id": "chanel",
    "name": "Chanel",
    "initials": "C",
    "category": "Мода / Косметика",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "chanel.com",
    "url": "https://www.chanel.com",
    "checked": "28.07.2026",
    "note": "Одяг haute couture, парфуми Chanel No. 5, косметика Рік заснування: 1910.",
    "year": "1910"
  },
  {
    "id": "herm-s",
    "name": "Hermès",
    "initials": "HS",
    "category": "Люкс / Аксесуари",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "hermes.com",
    "url": "https://www.hermes.com",
    "checked": "28.07.2026",
    "note": "Шкіряні сумки Birkin/Kelly, шовкові хустки Рік заснування: 1837.",
    "year": "1837"
  },
  {
    "id": "zara-inditex",
    "name": "Zara (Inditex)",
    "initials": "Z",
    "category": "Fast Fashion / Одяг",
    "country": "Іспанія",
    "countryCode": "ES",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "zara.com",
    "url": "https://www.zara.com",
    "checked": "28.07.2026",
    "note": "Трендовий повсякденний одяг, взуття, аксесуари Рік заснування: 1975.",
    "year": "1975"
  },
  {
    "id": "h-m",
    "name": "H&M",
    "initials": "HM",
    "category": "Модний одяг",
    "country": "Швеція",
    "countryCode": "SE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "www2.hm.com",
    "url": "https://www2.hm.com",
    "checked": "28.07.2026",
    "note": "Доступний повсякденний одяг для усієї родини Рік заснування: 1947.",
    "year": "1947"
  },
  {
    "id": "uniqlo",
    "name": "Uniqlo",
    "initials": "U",
    "category": "Повсякденний одяг",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "uniqlo.com",
    "url": "https://www.uniqlo.com",
    "checked": "28.07.2026",
    "note": "Базовий якісний одяг, термобілизна Heattech Рік заснування: 1949.",
    "year": "1949"
  },
  {
    "id": "puma",
    "name": "Puma",
    "initials": "P",
    "category": "Спортивні товари",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "puma.com",
    "url": "https://www.puma.com",
    "checked": "28.07.2026",
    "note": "Спортивне взуття, одяг для бігу та футболу Рік заснування: 1948.",
    "year": "1948"
  },
  {
    "id": "coca-cola",
    "name": "Coca-Cola",
    "initials": "CC",
    "category": "Безалкогольні напої",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "coca-colacompany.com",
    "url": "https://www.coca-colacompany.com",
    "checked": "28.07.2026",
    "note": "Напої Coca-Cola, Fanta, Sprite, Kinley Рік заснування: 1892.",
    "year": "1892"
  },
  {
    "id": "pepsico",
    "name": "PepsiCo",
    "initials": "P",
    "category": "Продукти харчування / Напої",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "pepsico.com",
    "url": "https://www.pepsico.com",
    "checked": "28.07.2026",
    "note": "Напої Pepsi, снеки Lay's, Doritos, Cheetos Рік заснування: 1965.",
    "year": "1965"
  },
  {
    "id": "nestl",
    "name": "Nestlé",
    "initials": "N",
    "category": "Продукти харчування",
    "country": "Швейцарія",
    "countryCode": "CH",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "nestle.com",
    "url": "https://www.nestle.com",
    "checked": "28.07.2026",
    "note": "Кава Nescafé, шоколад KitKat, дитяче харчування, вода Рік заснування: 1866.",
    "year": "1866"
  },
  {
    "id": "l-or-al",
    "name": "L'Oréal",
    "initials": "LO",
    "category": "Косметика та догляд",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "loreal.com",
    "url": "https://www.loreal.com",
    "checked": "28.07.2026",
    "note": "Косметика, засоби догляду за шкірою та волоссям Рік заснування: 1909.",
    "year": "1909"
  },
  {
    "id": "procter-gamble-p-g",
    "name": "Procter & Gamble (P&G)",
    "initials": "PG",
    "category": "Товари повсякденного попиту",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "us.pg.com",
    "url": "https://us.pg.com",
    "checked": "28.07.2026",
    "note": "Бренди Tide, Pampers, Gillette, Head & Shoulders Рік заснування: 1837.",
    "year": "1837"
  },
  {
    "id": "unilever",
    "name": "Unilever",
    "initials": "U",
    "category": "Споживчі товари",
    "country": "Великобританія",
    "countryCode": "GB",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "unilever.com",
    "url": "https://www.unilever.com",
    "checked": "28.07.2026",
    "note": "Бренди Dove, Lipton, Knorr, Ben & Jerry's Рік заснування: 1929.",
    "year": "1929"
  },
  {
    "id": "mcdonald-s",
    "name": "McDonald's",
    "initials": "MS",
    "category": "Швидке харчування",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "mcdonalds.com",
    "url": "https://www.mcdonalds.com",
    "checked": "28.07.2026",
    "note": "Мережа ресторанів швидкого обслуговування Рік заснування: 1940.",
    "year": "1940"
  },
  {
    "id": "starbucks",
    "name": "Starbucks",
    "initials": "S",
    "category": "Мережа кав'ярень",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "starbucks.com",
    "url": "https://www.starbucks.com",
    "checked": "28.07.2026",
    "note": "Кавові напої, кава в зернах, випічка Рік заснування: 1971.",
    "year": "1971"
  },
  {
    "id": "ikea",
    "name": "IKEA",
    "initials": "IK",
    "category": "Меблі та товари для дому",
    "country": "Швеція",
    "countryCode": "SE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "ikea.com",
    "url": "https://www.ikea.com",
    "checked": "28.07.2026",
    "note": "Складові меблі, предмети інтер'єру, домашній текстиль Рік заснування: 1943.",
    "year": "1943"
  },
  {
    "id": "amazon",
    "name": "Amazon",
    "initials": "A",
    "category": "Електронна комерція / Cloud",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "amazon.com",
    "url": "https://www.amazon.com",
    "checked": "28.07.2026",
    "note": "Маркетплейс, хмарні сервіси AWS, підписка Prime Рік заснування: 1994.",
    "year": "1994"
  },
  {
    "id": "netflix",
    "name": "Netflix",
    "initials": "N",
    "category": "Стрімінговий сервіс",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "netflix.com",
    "url": "https://www.netflix.com",
    "checked": "28.07.2026",
    "note": "Стрімінг фільмів, серіалів, оригінальний контент Рік заснування: 1997.",
    "year": "1997"
  },
  {
    "id": "spotify",
    "name": "Spotify",
    "initials": "S",
    "category": "Музичний стрімінг",
    "country": "Швеція",
    "countryCode": "SE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "spotify.com",
    "url": "https://www.spotify.com",
    "checked": "28.07.2026",
    "note": "Музичний сервіс, подкасти, аудіокниги Рік заснування: 2006.",
    "year": "2006"
  },
  {
    "id": "disney",
    "name": "Disney",
    "initials": "D",
    "category": "Розваги / Медіа",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "thewaltdisneycompany.com",
    "url": "https://thewaltdisneycompany.com",
    "checked": "28.07.2026",
    "note": "Анімація, кіностудії, тематичні парки, Disney+ Рік заснування: 1923.",
    "year": "1923"
  },
  {
    "id": "airbnb",
    "name": "Airbnb",
    "initials": "A",
    "category": "Онлайн-сервіс житла",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "airbnb.com",
    "url": "https://www.airbnb.com",
    "checked": "28.07.2026",
    "note": "Платформа для бронювання житла та вражень Рік заснування: 2008.",
    "year": "2008"
  },
  {
    "id": "booking-com",
    "name": "Booking.com",
    "initials": "BC",
    "category": "Туризм та бронювання",
    "country": "Нідерланди",
    "countryCode": "NL",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "booking.com",
    "url": "https://www.booking.com",
    "checked": "28.07.2026",
    "note": "Сервіс бронювання готелів, авіаквитків, авто Рік заснування: 1996.",
    "year": "1996"
  },
  {
    "id": "visa",
    "name": "Visa",
    "initials": "V",
    "category": "Фінансові послуги / Платежі",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "visa.com",
    "url": "https://www.visa.com",
    "checked": "28.07.2026",
    "note": "Платіжна система, дебетові та кредитні картки Рік заснування: 1958.",
    "year": "1958"
  },
  {
    "id": "mastercard",
    "name": "Mastercard",
    "initials": "M",
    "category": "Фінансові послуги",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "mastercard.com",
    "url": "https://www.mastercard.com",
    "checked": "28.07.2026",
    "note": "Глобальна платіжна система та технології Рік заснування: 1966.",
    "year": "1966"
  },
  {
    "id": "paypal",
    "name": "PayPal",
    "initials": "P",
    "category": "Електронні платежі",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "paypal.com",
    "url": "https://www.paypal.com",
    "checked": "28.07.2026",
    "note": "Онлайн-перекази, електронний гаманець Рік заснування: 1998.",
    "year": "1998"
  },
  {
    "id": "lego",
    "name": "Lego",
    "initials": "L",
    "category": "Іграшки / Конструктори",
    "country": "Данія",
    "countryCode": "DK",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "lego.com",
    "url": "https://www.lego.com",
    "checked": "28.07.2026",
    "note": "Пластикові конструктори для дітей та дорослих Рік заснування: 1932.",
    "year": "1932"
  },
  {
    "id": "red-bull",
    "name": "Red Bull",
    "initials": "RB",
    "category": "Енергетичні напої / Спорт",
    "country": "Австрія",
    "countryCode": "AT",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "redbull.com",
    "url": "https://www.redbull.com",
    "checked": "28.07.2026",
    "note": "Енергетичні напої, спонсорство екстремального спорту Рік заснування: 1987.",
    "year": "1987"
  },
  {
    "id": "xiaomi",
    "name": "Xiaomi",
    "initials": "X",
    "category": "Електроніка / Смартфони",
    "country": "Китай",
    "countryCode": "CN",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "mi.com",
    "url": "https://www.mi.com",
    "checked": "28.07.2026",
    "note": "Смартфони, пристрої розумного дому, електротранспорт Рік заснування: 2010.",
    "year": "2010"
  },
  {
    "id": "lenovo",
    "name": "Lenovo",
    "initials": "L",
    "category": "Комп'ютерна техніка",
    "country": "Китай",
    "countryCode": "CN",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "lenovo.com",
    "url": "https://www.lenovo.com",
    "checked": "28.07.2026",
    "note": "Ноутбуки ThinkPad/Yoga, ПК, сервери, планшети Рік заснування: 1984.",
    "year": "1984"
  },
  {
    "id": "hp-hewlett-packard",
    "name": "HP (Hewlett-Packard)",
    "initials": "HP",
    "category": "Комп'ютери та друк",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "hp.com",
    "url": "https://www.hp.com",
    "checked": "28.07.2026",
    "note": "Ноутбуки Spectre/Pavilion, принтери, БФП, витратні матеріали Рік заснування: 1939.",
    "year": "1939"
  },
  {
    "id": "canon",
    "name": "Canon",
    "initials": "C",
    "category": "Фототехніка / Оптика",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "global.canon",
    "url": "https://global.canon",
    "checked": "28.07.2026",
    "note": "Фотокамери EOS, об'єктиви, сканери, медобладнання Рік заснування: 1937.",
    "year": "1937"
  },
  {
    "id": "nikon",
    "name": "Nikon",
    "initials": "N",
    "category": "Оптичні прилади / Фото",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "nikon.com",
    "url": "https://www.nikon.com",
    "checked": "28.07.2026",
    "note": "Дзеркальні та бездзеркальні фотокамери Z-серії, оптика Рік заснування: 1917.",
    "year": "1917"
  },
  {
    "id": "garmin",
    "name": "Garmin",
    "initials": "G",
    "category": "GPS-навігація / Смартгодинники",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "garmin.com",
    "url": "https://www.garmin.com",
    "checked": "28.07.2026",
    "note": "Спортивні смартгодинники, навігатори, авіаційне обладнання Рік заснування: 1989.",
    "year": "1989"
  },
  {
    "id": "panasonic",
    "name": "Panasonic",
    "initials": "P",
    "category": "Побутова техніка / Електроніка",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "panasonic.com",
    "url": "https://www.panasonic.com",
    "checked": "28.07.2026",
    "note": "Аудіотехніка, камери Lumix, акумулятори, кліматична техніка Рік заснування: 1918.",
    "year": "1918"
  },
  {
    "id": "philips",
    "name": "Philips",
    "initials": "P",
    "category": "Охорона здоров'я / Побутова техніка",
    "country": "Нідерланди",
    "countryCode": "NL",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "philips.com",
    "url": "https://www.philips.com",
    "checked": "28.07.2026",
    "note": "Медичне обладнання, бритви, електрозчітки, техніка для дому Рік заснування: 1891.",
    "year": "1891"
  },
  {
    "id": "siemens",
    "name": "Siemens",
    "initials": "S",
    "category": "Промисловість / Автоматизація",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "siemens.com",
    "url": "https://www.siemens.com",
    "checked": "28.07.2026",
    "note": "Промислова автоматизація, енергетика, медичні технології Рік заснування: 1847.",
    "year": "1847"
  },
  {
    "id": "cisco",
    "name": "Cisco",
    "initials": "C",
    "category": "Мережеве обладнання / IT",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "cisco.com",
    "url": "https://www.cisco.com",
    "checked": "28.07.2026",
    "note": "Маршрутизатори, комутатори, рішення з кібербезпеки Рік заснування: 1984.",
    "year": "1984"
  },
  {
    "id": "audi",
    "name": "Audi",
    "initials": "A",
    "category": "Преміум-автомобілі",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "audi.com",
    "url": "https://www.audi.com",
    "checked": "28.07.2026",
    "note": "Легкові авто, спортивні моделі RS, електромобілі e-tron Рік заснування: 1909.",
    "year": "1909"
  },
  {
    "id": "volvo",
    "name": "Volvo",
    "initials": "V",
    "category": "Автомобілі / Безпека",
    "country": "Швеція",
    "countryCode": "SE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "volvocars.com",
    "url": "https://www.volvocars.com",
    "checked": "28.07.2026",
    "note": "Легкові авто, кросовери XC, вантажне транспортне обладнання Рік заснування: 1927.",
    "year": "1927"
  },
  {
    "id": "nissan",
    "name": "Nissan",
    "initials": "N",
    "category": "Автомобілебудування",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "nissan-global.com",
    "url": "https://www.nissan-global.com",
    "checked": "28.07.2026",
    "note": "Автомобілі Qashqai/X-Trail, електромобілі Leaf Рік заснування: 1933.",
    "year": "1933"
  },
  {
    "id": "kia",
    "name": "Kia",
    "initials": "K",
    "category": "Автомобілебудування",
    "country": "Південна Корея",
    "countryCode": "KR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "kia.com",
    "url": "https://www.kia.com",
    "checked": "28.07.2026",
    "note": "Кросовери Sportage, електромобілі EV6, легкові авто Рік заснування: 1944.",
    "year": "1944"
  },
  {
    "id": "mazda",
    "name": "Mazda",
    "initials": "M",
    "category": "Автомобілебудування",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "mazda.com",
    "url": "https://www.mazda.com",
    "checked": "28.07.2026",
    "note": "Легкові авто та кросовери CX-серії з технологією Skyactiv Рік заснування: 1920.",
    "year": "1920"
  },
  {
    "id": "subaru",
    "name": "Subaru",
    "initials": "S",
    "category": "Автомобілі / Повний привід",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "subaru-global.com",
    "url": "https://www.subaru-global.com",
    "checked": "28.07.2026",
    "note": "Позашляховики Forester/Outback, симетричний повний привід Рік заснування: 1953.",
    "year": "1953"
  },
  {
    "id": "jaguar-land-rover",
    "name": "Jaguar Land Rover",
    "initials": "JL",
    "category": "Преміум-позашляховики",
    "country": "Великобританія",
    "countryCode": "GB",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "jaguarlandrover.com",
    "url": "https://www.jaguarlandrover.com",
    "checked": "28.07.2026",
    "note": "Люксові позашляховики Range Rover, Defender, авто Jaguar Рік заснування: 2008.",
    "year": "2008"
  },
  {
    "id": "aston-martin",
    "name": "Aston Martin",
    "initials": "AM",
    "category": "Спортивні авто люкс-класу",
    "country": "Великобританія",
    "countryCode": "GB",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "astonmartin.com",
    "url": "https://www.astonmartin.com",
    "checked": "28.07.2026",
    "note": "Елітні спортивні автомобілі, культові британські купе Рік заснування: 1913.",
    "year": "1913"
  },
  {
    "id": "michelin",
    "name": "Michelin",
    "initials": "M",
    "category": "Виробництво шин",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "michelin.com",
    "url": "https://www.michelin.com",
    "checked": "28.07.2026",
    "note": "Автомобільні шини, гід по ресторанах Michelin Guide Рік заснування: 1889.",
    "year": "1889"
  },
  {
    "id": "bridgestone",
    "name": "Bridgestone",
    "initials": "B",
    "category": "Шини / Гумові вироби",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "bridgestone.com",
    "url": "https://www.bridgestone.com",
    "checked": "28.07.2026",
    "note": "Автомобільні та промислові шини для різних видів транспорту Рік заснування: 1931.",
    "year": "1931"
  },
  {
    "id": "new-balance",
    "name": "New Balance",
    "initials": "NB",
    "category": "Спортивне взуття",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "newbalance.com",
    "url": "https://www.newbalance.com",
    "checked": "28.07.2026",
    "note": "Кросівки для бігу та повсякденного життя (серії 574, 990) Рік заснування: 1906.",
    "year": "1906"
  },
  {
    "id": "prada",
    "name": "Prada",
    "initials": "P",
    "category": "Люкс / Мода",
    "country": "Італія",
    "countryCode": "IT",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "prada.com",
    "url": "https://www.prada.com",
    "checked": "28.07.2026",
    "note": "Елітний одяг, шкіряні сумки, аксесуари, парфумерія Рік заснування: 1913.",
    "year": "1913"
  },
  {
    "id": "rolex",
    "name": "Rolex",
    "initials": "R",
    "category": "Преміум-годинники",
    "country": "Швейцарія",
    "countryCode": "CH",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "rolex.com",
    "url": "https://www.rolex.com",
    "checked": "28.07.2026",
    "note": "Елітні механічні годинники Submariner, Daytona, Datejust Рік заснування: 1905.",
    "year": "1905"
  },
  {
    "id": "cartier",
    "name": "Cartier",
    "initials": "C",
    "category": "Ювелірні вироби / Годинники",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "cartier.com",
    "url": "https://www.cartier.com",
    "checked": "28.07.2026",
    "note": "Ювелірні прикраси Love/Juste un Clou, розкішні годинники Рік заснування: 1847.",
    "year": "1847"
  },
  {
    "id": "tiffany-co",
    "name": "Tiffany & Co.",
    "initials": "TC",
    "category": "Ювелірні вироби",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "tiffany.com",
    "url": "https://www.tiffany.com",
    "checked": "28.07.2026",
    "note": "Діамантові прикраси, обручки, срібні вироби Рік заснування: 1837.",
    "year": "1837"
  },
  {
    "id": "sephora",
    "name": "Sephora",
    "initials": "S",
    "category": "Мережа косметики",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "sephora.com",
    "url": "https://www.sephora.com",
    "checked": "28.07.2026",
    "note": "Мультибрендові магазини парфумерії, макіяжу та догляду Рік заснування: 1969.",
    "year": "1969"
  },
  {
    "id": "est-e-lauder",
    "name": "Estée Lauder",
    "initials": "EE",
    "category": "Косметика та догляд",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "esteelauder.com",
    "url": "https://www.esteelauder.com",
    "checked": "28.07.2026",
    "note": "Антивіковий догляд, парфумерія, декоративна косметика Рік заснування: 1946.",
    "year": "1946"
  },
  {
    "id": "tommy-hilfiger",
    "name": "Tommy Hilfiger",
    "initials": "TH",
    "category": "Преміум-одяг",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "tommy.com",
    "url": "https://www.tommy.com",
    "checked": "28.07.2026",
    "note": "Одяг у стилі casual/preppy, джинсові колекції Рік заснування: 1985.",
    "year": "1985"
  },
  {
    "id": "calvin-klein",
    "name": "Calvin Klein",
    "initials": "CK",
    "category": "Мода / Білизна",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "calvinklein.com",
    "url": "https://www.calvinklein.com",
    "checked": "28.07.2026",
    "note": "Нижня білизна, джинсовий одяг, парфумерія Рік заснування: 1968.",
    "year": "1968"
  },
  {
    "id": "under-armour",
    "name": "Under Armour",
    "initials": "UA",
    "category": "Спортивний одяг",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "underarmour.com",
    "url": "https://www.underarmour.com",
    "checked": "28.07.2026",
    "note": "Компресійний одяг, кросівки для тренувань, аксесуари Рік заснування: 1996.",
    "year": "1996"
  },
  {
    "id": "heineken",
    "name": "Heineken",
    "initials": "H",
    "category": "Пивоваріння",
    "country": "Нідерланди",
    "countryCode": "NL",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "theheinekencompany.com",
    "url": "https://www.theheinekencompany.com",
    "checked": "28.07.2026",
    "note": "Преміальне пиво, міжнародні алкогольні бренди Рік заснування: 1864.",
    "year": "1864"
  },
  {
    "id": "danone",
    "name": "Danone",
    "initials": "D",
    "category": "Молочні продукты / Харчування",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "danone.com",
    "url": "https://www.danone.com",
    "checked": "28.07.2026",
    "note": "Йогурти Activia, дитяче харчування, мінеральна вода Evian Рік заснування: 1919.",
    "year": "1919"
  },
  {
    "id": "mars-incorporated",
    "name": "Mars, Incorporated",
    "initials": "MI",
    "category": "Кондитерські вироби / Корми",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "mars.com",
    "url": "https://www.mars.com",
    "checked": "28.07.2026",
    "note": "Шоколад Snickers/M&M's, корми для тварин Pedigree/Whiskas Рік заснування: 1911.",
    "year": "1911"
  },
  {
    "id": "ferrero",
    "name": "Ferrero",
    "initials": "F",
    "category": "Кондитерські вироби",
    "country": "Італія",
    "countryCode": "IT",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "ferrero.com",
    "url": "https://www.ferrero.com",
    "checked": "28.07.2026",
    "note": "Паста Nutella, солодощі Ferrero Rocher, Kinder, Tic Tac Рік заснування: 1946.",
    "year": "1946"
  },
  {
    "id": "mondelez-international",
    "name": "Mondelez International",
    "initials": "MI",
    "category": "Снеки та солодощі",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "mondelezinternational.com",
    "url": "https://www.mondelezinternational.com",
    "checked": "28.07.2026",
    "note": "Шоколад Milka, печиво Oreo, Barni, сир Philadelphia Рік заснування: 2012.",
    "year": "2012"
  },
  {
    "id": "kfc",
    "name": "KFC",
    "initials": "KF",
    "category": "Швидке харчування",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "kfc.com",
    "url": "https://www.kfc.com",
    "checked": "28.07.2026",
    "note": "Мережа ресторанів, страви з курятини за таємним рецептом Рік заснування: 1952.",
    "year": "1952"
  },
  {
    "id": "burger-king",
    "name": "Burger King",
    "initials": "BK",
    "category": "Швидке харчування",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "bk.com",
    "url": "https://www.bk.com",
    "checked": "28.07.2026",
    "note": "Мережа ресторанів швидкого харчування, бургери Whopper Рік заснування: 1954.",
    "year": "1954"
  },
  {
    "id": "nespresso",
    "name": "Nespresso",
    "initials": "N",
    "category": "Кавові системи",
    "country": "Швейцарія",
    "countryCode": "CH",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "nespresso.com",
    "url": "https://www.nespresso.com",
    "checked": "28.07.2026",
    "note": "Капсульні кавомашини, сортові кавові капсули Рік заснування: 1986.",
    "year": "1986"
  },
  {
    "id": "decathlon",
    "name": "Decathlon",
    "initials": "D",
    "category": "Спортивні товари",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "decathlon.com",
    "url": "https://www.decathlon.com",
    "checked": "28.07.2026",
    "note": "Мережа супермаркетів товарів для спорту та туризму Рік заснування: 1976.",
    "year": "1976"
  },
  {
    "id": "lidl",
    "name": "Lidl",
    "initials": "L",
    "category": "Мережа супермаркетів",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "lidl.com",
    "url": "https://www.lidl.com",
    "checked": "28.07.2026",
    "note": "Міжнародна мережа супермаркетів-дискаунтерів Рік заснування: 1973.",
    "year": "1973"
  },
  {
    "id": "adobe",
    "name": "Adobe",
    "initials": "A",
    "category": "Програмне забезпечення / Графіка",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "adobe.com",
    "url": "https://www.adobe.com",
    "checked": "28.07.2026",
    "note": "Photoshop, Illustrator, Premiere Pro, PDF Reader Рік заснування: 1982.",
    "year": "1982"
  },
  {
    "id": "uber",
    "name": "Uber",
    "initials": "U",
    "category": "Таксі / Доставка",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "uber.com",
    "url": "https://www.uber.com",
    "checked": "28.07.2026",
    "note": "Онлайн-сервіс виклику авто, доставка їжі Uber Eats Рік заснування: 2009.",
    "year": "2009"
  },
  {
    "id": "siemens-healthineers",
    "name": "Siemens Healthineers",
    "initials": "SH",
    "category": "Медична техніка",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "siemens-healthineers.com",
    "url": "https://www.siemens-healthineers.com",
    "checked": "28.07.2026",
    "note": "Томографи МРТ/КТ, лабораторна діагностика Рік заснування: 2015.",
    "year": "2015"
  },
  {
    "id": "nintendo",
    "name": "Nintendo",
    "initials": "N",
    "category": "Відеоігри / Консолі",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "nintendo.com",
    "url": "https://www.nintendo.com",
    "checked": "28.07.2026",
    "note": "Ігрові консолі Switch, франшизи Mario, Zelda, Pokémon Рік заснування: 1889.",
    "year": "1889"
  },
  {
    "id": "swarovski",
    "name": "Swarovski",
    "initials": "S",
    "category": "Кришталь / Прикраси",
    "country": "Австрія",
    "countryCode": "AT",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "swarovski.com",
    "url": "https://www.swarovski.com",
    "checked": "28.07.2026",
    "note": "Вироби з кришталю, ювелірні прикраси, декор Рік заснування: 1895.",
    "year": "1895"
  },
  {
    "id": "logitech",
    "name": "Logitech",
    "initials": "L",
    "category": "Комп'ютерна периферія",
    "country": "Швейцарія",
    "countryCode": "CH",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "logitech.com",
    "url": "https://www.logitech.com",
    "checked": "28.07.2026",
    "note": "Миші, клавіатури, вебкамери, акустика Рік заснування: 1981.",
    "year": "1981"
  },
  {
    "id": "dji",
    "name": "DJI",
    "initials": "DJ",
    "category": "Дрони / Аерозйомка",
    "country": "Китай",
    "countryCode": "CN",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "dji.com",
    "url": "https://www.dji.com",
    "checked": "28.07.2026",
    "note": "Безпілотники Mavic/Phantom, стедіками, екшн-камери Рік заснування: 2006.",
    "year": "2006"
  },
  {
    "id": "gopro",
    "name": "GoPro",
    "initials": "G",
    "category": "Екшн-камери",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "gopro.com",
    "url": "https://gopro.com",
    "checked": "28.07.2026",
    "note": "Компактні екшн-камери HERO, аксесуари для зйомки Рік заснування: 2002.",
    "year": "2002"
  },
  {
    "id": "k-rcher",
    "name": "Kärcher",
    "initials": "KR",
    "category": "Збиральна техніка",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "kaercher.com",
    "url": "https://www.kaercher.com",
    "checked": "28.07.2026",
    "note": "Мийки високого тиску, пилососи, технічні засоби чищення Рік заснування: 1935.",
    "year": "1935"
  },
  {
    "id": "barilla",
    "name": "Barilla",
    "initials": "B",
    "category": "Харчова промисловість",
    "country": "Італія",
    "countryCode": "IT",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "barillagroup.com",
    "url": "https://www.barillagroup.com",
    "checked": "28.07.2026",
    "note": "Італійські макаронні вироби (паста), соуси Рік заснування: 1877.",
    "year": "1877"
  }
];
