window.BRAND_DATA = [
  {
    "id": "apple",
    "name": "Apple",
    "initials": "A",
    "category": "Технології / Електроніка",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "apple.com",
    "url": "https://www.apple.com",
    "checked": "28.07.2026",
    "note": "Смартфони iPhone, ПК Mac, планшети iPad, ОС iOS Рік заснування: 1976.",
    "year": "1976"
  },
  {
    "id": "microsoft",
    "name": "Microsoft",
    "initials": "M",
    "category": "ПО / Хмарні сервіси",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "microsoft.com",
    "url": "https://www.microsoft.com",
    "checked": "28.07.2026",
    "note": "Операційна система Windows, MS Office, Azure, Xbox Рік заснування: 1975.",
    "year": "1975"
  },
  {
    "id": "google-alphabet",
    "name": "Google (Alphabet)",
    "initials": "G",
    "category": "Інтернет-сервіси / ПО",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "google.com",
    "url": "https://www.google.com",
    "checked": "28.07.2026",
    "note": "Пошукова система, Android, YouTube, Google Cloud Рік заснування: 1998.",
    "year": "1998"
  },
  {
    "id": "samsung",
    "name": "Samsung",
    "initials": "S",
    "category": "Електроніка / Технології",
    "country": "Південна Корея",
    "countryCode": "KR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "samsung.com",
    "url": "https://www.samsung.com",
    "checked": "28.07.2026",
    "note": "Смартфони Galaxy, побутова техніка, дисплеї Рік заснування: 1938.",
    "year": "1938"
  },
  {
    "id": "sony",
    "name": "Sony",
    "initials": "S",
    "category": "Електроніка / Розваги",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "sony.com",
    "url": "https://www.sony.com",
    "checked": "28.07.2026",
    "note": "Ігрові консолі PlayStation, аудіо, фотокамери Рік заснування: 1946.",
    "year": "1946"
  },
  {
    "id": "nvidia",
    "name": "NVIDIA",
    "initials": "NV",
    "category": "Напівпровідники / AI",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "nvidia.com",
    "url": "https://www.nvidia.com",
    "checked": "28.07.2026",
    "note": "Графічні процесори GeForce, чіпи для ШІ Рік заснування: 1993.",
    "year": "1993"
  },
  {
    "id": "intel",
    "name": "Intel",
    "initials": "I",
    "category": "Напівпровідники",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "intel.com",
    "url": "https://www.intel.com",
    "checked": "28.07.2026",
    "note": "Мікропроцесори Core, Xeon, обладнання для ПК Рік заснування: 1968.",
    "year": "1968"
  },
  {
    "id": "dell-technologies",
    "name": "Dell Technologies",
    "initials": "DT",
    "category": "Комп'ютерна техніка",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "dell.com",
    "url": "https://www.dell.com",
    "checked": "28.07.2026",
    "note": "Ноутбуки, сервери, монітори, IT-рішення Рік заснування: 1984.",
    "year": "1984"
  },
  {
    "id": "lg-electronics",
    "name": "LG Electronics",
    "initials": "LE",
    "category": "Побутова техніка / Електроніка",
    "country": "Південна Корея",
    "countryCode": "KR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "lg.com",
    "url": "https://www.lg.com",
    "checked": "28.07.2026",
    "note": "Телевізори OLED, холодильники, пральні машини Рік заснування: 1958.",
    "year": "1958"
  },
  {
    "id": "asus",
    "name": "ASUS",
    "initials": "AS",
    "category": "Комп'ютерна техніка",
    "country": "Тайвань",
    "countryCode": "TW",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "asus.com",
    "url": "https://www.asus.com",
    "checked": "28.07.2026",
    "note": "Ноутбуки ROG/ZenBook, материнські плати, монітори Рік заснування: 1989.",
    "year": "1989"
  },
  {
    "id": "toyota",
    "name": "Toyota",
    "initials": "T",
    "category": "Автомобілебудування",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "toyota.com",
    "url": "https://www.toyota.com",
    "checked": "28.07.2026",
    "note": "Легкові автомобілі, гібриди, позашляховики Рік заснування: 1937.",
    "year": "1937"
  },
  {
    "id": "volkswagen",
    "name": "Volkswagen",
    "initials": "V",
    "category": "Автомобілебудування",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "volkswagen.com",
    "url": "https://www.volkswagen.com",
    "checked": "28.07.2026",
    "note": "Авто VW, групи Audi, Porsche, Skoda Рік заснування: 1937.",
    "year": "1937"
  },
  {
    "id": "bmw",
    "name": "BMW",
    "initials": "BM",
    "category": "Преміум-автомобілі",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "bmw.com",
    "url": "https://www.bmw.com",
    "checked": "28.07.2026",
    "note": "Автомобілі BMW, мотоцикли, Rolls-Royce Рік заснування: 1916.",
    "year": "1916"
  },
  {
    "id": "mercedes-benz",
    "name": "Mercedes-Benz",
    "initials": "MB",
    "category": "Преміум-автомобілі",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "mercedes-benz.com",
    "url": "https://www.mercedes-benz.com",
    "checked": "28.07.2026",
    "note": "Легкові автомобілі, люкс-сегмент, вантажівки Рік заснування: 1926.",
    "year": "1926"
  },
  {
    "id": "tesla",
    "name": "Tesla",
    "initials": "T",
    "category": "Електромобілі / Енергетика",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "tesla.com",
    "url": "https://www.tesla.com",
    "checked": "28.07.2026",
    "note": "Електромобілі Model S/3/X/Y, акумулятори Рік заснування: 2003.",
    "year": "2003"
  },
  {
    "id": "ford",
    "name": "Ford",
    "initials": "F",
    "category": "Автомобілебудування",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "ford.com",
    "url": "https://www.ford.com",
    "checked": "28.07.2026",
    "note": "Легкові автомобілі, пікапи F-150, позашляховики Рік заснування: 1903.",
    "year": "1903"
  },
  {
    "id": "honda",
    "name": "Honda",
    "initials": "H",
    "category": "Автомобілі / Мототехніка",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "global.honda",
    "url": "https://global.honda",
    "checked": "28.07.2026",
    "note": "Автомобілі, мотоцикли, силова техніка Рік заснування: 1948.",
    "year": "1948"
  },
  {
    "id": "hyundai",
    "name": "Hyundai",
    "initials": "H",
    "category": "Автомобілебудування",
    "country": "Південна Корея",
    "countryCode": "KR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "hyundai.com",
    "url": "https://www.hyundai.com",
    "checked": "28.07.2026",
    "note": "Легкові автомобілі, електромобілі Ioniq Рік заснування: 1967.",
    "year": "1967"
  },
  {
    "id": "porsche",
    "name": "Porsche",
    "initials": "P",
    "category": "Спортивні автомобілі",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "porsche.com",
    "url": "https://www.porsche.com",
    "checked": "28.07.2026",
    "note": "Спортивні автомобілі 911, Cayenne, Taycan Рік заснування: 1931.",
    "year": "1931"
  },
  {
    "id": "ferrari",
    "name": "Ferrari",
    "initials": "F",
    "category": "Суперкари / Автоспорт",
    "country": "Італія",
    "countryCode": "IT",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "ferrari.com",
    "url": "https://www.ferrari.com",
    "checked": "28.07.2026",
    "note": "Преміальні суперкари, команда Formula 1 Рік заснування: 1939.",
    "year": "1939"
  },
  {
    "id": "nike",
    "name": "Nike",
    "initials": "N",
    "category": "Спортивне взуття та одяг",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "nike.com",
    "url": "https://www.nike.com",
    "checked": "28.07.2026",
    "note": "Кросівки Air Max/Jordan, спортивне екіпірування Рік заснування: 1964.",
    "year": "1964"
  },
  {
    "id": "adidas",
    "name": "Adidas",
    "initials": "A",
    "category": "Спортивний одяг та взуття",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "adidas.com",
    "url": "https://www.adidas.com",
    "checked": "28.07.2026",
    "note": "Кросівки Originals/Boost, спортивне спорядження Рік заснування: 1949.",
    "year": "1949"
  },
  {
    "id": "louis-vuitton",
    "name": "Louis Vuitton",
    "initials": "LV",
    "category": "Люкс / Мода",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "louisvuitton.com",
    "url": "https://www.louisvuitton.com",
    "checked": "28.07.2026",
    "note": "Сумки, аксесуари, одяг високої моди Рік заснування: 1854.",
    "year": "1854"
  },
  {
    "id": "gucci",
    "name": "Gucci",
    "initials": "G",
    "category": "Люкс / Мода",
    "country": "Італія",
    "countryCode": "IT",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "gucci.com",
    "url": "https://www.gucci.com",
    "checked": "28.07.2026",
    "note": "Преміум одяг, шкіряні вироби, парфумерія Рік заснування: 1921.",
    "year": "1921"
  },
  {
    "id": "chanel",
    "name": "Chanel",
    "initials": "C",
    "category": "Мода / Косметика",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "chanel.com",
    "url": "https://www.chanel.com",
    "checked": "28.07.2026",
    "note": "Одяг haute couture, парфуми, косметика Рік заснування: 1910.",
    "year": "1910"
  },
  {
    "id": "herm-s",
    "name": "Hermès",
    "initials": "HS",
    "category": "Люкс / Аксесуари",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "hermes.com",
    "url": "https://www.hermes.com",
    "checked": "28.07.2026",
    "note": "Шкіряні сумки Birkin/Kelly, шовкові хустки Рік заснування: 1837.",
    "year": "1837"
  },
  {
    "id": "zara",
    "name": "Zara",
    "initials": "Z",
    "category": "Fast Fashion / Одяг",
    "country": "Іспанія",
    "countryCode": "ES",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "zara.com",
    "url": "https://www.zara.com",
    "checked": "28.07.2026",
    "note": "Трендовий повсякденний одяг, взуття Рік заснування: 1975.",
    "year": "1975"
  },
  {
    "id": "h-m",
    "name": "H&M",
    "initials": "HM",
    "category": "Модний одяг",
    "country": "Швеція",
    "countryCode": "SE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "www2.hm.com",
    "url": "https://www2.hm.com",
    "checked": "28.07.2026",
    "note": "Доступний повсякденний одяг Рік заснування: 1947.",
    "year": "1947"
  },
  {
    "id": "uniqlo",
    "name": "Uniqlo",
    "initials": "U",
    "category": "Повсякденний одяг",
    "country": "Японія",
    "countryCode": "JP",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "uniqlo.com",
    "url": "https://www.uniqlo.com",
    "checked": "28.07.2026",
    "note": "Базовий якісний одяг, термобілизна Heattech Рік заснування: 1949.",
    "year": "1949"
  },
  {
    "id": "puma",
    "name": "Puma",
    "initials": "P",
    "category": "Спортивні товари",
    "country": "Німеччина",
    "countryCode": "DE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "puma.com",
    "url": "https://www.puma.com",
    "checked": "28.07.2026",
    "note": "Спортивне взуття, одяг для бігу та футболу Рік заснування: 1948.",
    "year": "1948"
  },
  {
    "id": "coca-cola",
    "name": "Coca-Cola",
    "initials": "CC",
    "category": "Безалкогольні напої",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "coca-colacompany.com",
    "url": "https://www.coca-colacompany.com",
    "checked": "28.07.2026",
    "note": "Напої Coca-Cola, Fanta, Sprite, Kinley Рік заснування: 1892.",
    "year": "1892"
  },
  {
    "id": "pepsico",
    "name": "PepsiCo",
    "initials": "P",
    "category": "Продукти харчування / Напої",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "pepsico.com",
    "url": "https://www.pepsico.com",
    "checked": "28.07.2026",
    "note": "Напої Pepsi, снеки Lay's, Doritos, Cheetos Рік заснування: 1965.",
    "year": "1965"
  },
  {
    "id": "nestl",
    "name": "Nestlé",
    "initials": "N",
    "category": "Продукти харчування",
    "country": "Швейцарія",
    "countryCode": "CH",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "nestle.com",
    "url": "https://www.nestle.com",
    "checked": "28.07.2026",
    "note": "Кава Nescafé, шоколад KitKat, дитяче харчування Рік заснування: 1866.",
    "year": "1866"
  },
  {
    "id": "l-or-al",
    "name": "L'Oréal",
    "initials": "LO",
    "category": "Косметика та догляд",
    "country": "Франція",
    "countryCode": "FR",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "loreal.com",
    "url": "https://www.loreal.com",
    "checked": "28.07.2026",
    "note": "Косметика, засоби догляду за шкірою та волоссям Рік заснування: 1909.",
    "year": "1909"
  },
  {
    "id": "procter-gamble",
    "name": "Procter & Gamble",
    "initials": "PG",
    "category": "Товари повсякденного попиту",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "us.pg.com",
    "url": "https://us.pg.com",
    "checked": "28.07.2026",
    "note": "Бренди Tide, Pampers, Gillette, Head & Shoulders Рік заснування: 1837.",
    "year": "1837"
  },
  {
    "id": "unilever",
    "name": "Unilever",
    "initials": "U",
    "category": "Споживчі товари",
    "country": "Великобританія",
    "countryCode": "GB",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "unilever.com",
    "url": "https://www.unilever.com",
    "checked": "28.07.2026",
    "note": "Бренди Dove, Lipton, Knorr, Ben & Jerry's Рік заснування: 1929.",
    "year": "1929"
  },
  {
    "id": "mcdonald-s",
    "name": "McDonald's",
    "initials": "MS",
    "category": "Швидке харчування",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "mcdonalds.com",
    "url": "https://www.mcdonalds.com",
    "checked": "28.07.2026",
    "note": "Мережа ресторанів швидкого обслуговування Рік заснування: 1940.",
    "year": "1940"
  },
  {
    "id": "starbucks",
    "name": "Starbucks",
    "initials": "S",
    "category": "Мережа кав'ярень",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "starbucks.com",
    "url": "https://www.starbucks.com",
    "checked": "28.07.2026",
    "note": "Кавові напої, кава в зернах, випічка Рік заснування: 1971.",
    "year": "1971"
  },
  {
    "id": "ikea",
    "name": "IKEA",
    "initials": "IK",
    "category": "Меблі та товари для дому",
    "country": "Швеція",
    "countryCode": "SE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "ikea.com",
    "url": "https://www.ikea.com",
    "checked": "28.07.2026",
    "note": "Складові меблі, предмети інтер'єру Рік заснування: 1943.",
    "year": "1943"
  },
  {
    "id": "amazon",
    "name": "Amazon",
    "initials": "A",
    "category": "Електронна комерція / Cloud",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "amazon.com",
    "url": "https://www.amazon.com",
    "checked": "28.07.2026",
    "note": "Маркетплейс, хмарні сервіси AWS, Prime Рік заснування: 1994.",
    "year": "1994"
  },
  {
    "id": "netflix",
    "name": "Netflix",
    "initials": "N",
    "category": "Стрімінговий сервіс",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "netflix.com",
    "url": "https://www.netflix.com",
    "checked": "28.07.2026",
    "note": "Стрімінг фільмів, серіалів, оригінальний контент Рік заснування: 1997.",
    "year": "1997"
  },
  {
    "id": "spotify",
    "name": "Spotify",
    "initials": "S",
    "category": "Музичний стрімінг",
    "country": "Швеція",
    "countryCode": "SE",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "spotify.com",
    "url": "https://www.spotify.com",
    "checked": "28.07.2026",
    "note": "Музичний сервіс, подкасти, аудіокниги Рік заснування: 2006.",
    "year": "2006"
  },
  {
    "id": "disney",
    "name": "Disney",
    "initials": "D",
    "category": "Розваги / Медіа",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "thewaltdisneycompany.com",
    "url": "https://thewaltdisneycompany.com",
    "checked": "28.07.2026",
    "note": "Анімація, кіностудії, парки, Disney+ Рік заснування: 1923.",
    "year": "1923"
  },
  {
    "id": "airbnb",
    "name": "Airbnb",
    "initials": "A",
    "category": "Онлайн-сервіс житла",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "airbnb.com",
    "url": "https://www.airbnb.com",
    "checked": "28.07.2026",
    "note": "Платформа для бронювання житла та вражень Рік заснування: 2008.",
    "year": "2008"
  },
  {
    "id": "booking-com",
    "name": "Booking.com",
    "initials": "BC",
    "category": "Туризм та бронювання",
    "country": "Нідерланди",
    "countryCode": "NL",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "booking.com",
    "url": "https://www.booking.com",
    "checked": "28.07.2026",
    "note": "Бронювання готелів, авіаквитків, авто Рік заснування: 1996.",
    "year": "1996"
  },
  {
    "id": "visa",
    "name": "Visa",
    "initials": "V",
    "category": "Фінансові послуги / Платежі",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "visa.com",
    "url": "https://www.visa.com",
    "checked": "28.07.2026",
    "note": "Платіжна система, дебетові та кредитні картки Рік заснування: 1958.",
    "year": "1958"
  },
  {
    "id": "mastercard",
    "name": "Mastercard",
    "initials": "M",
    "category": "Фінансові послуги",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "mastercard.com",
    "url": "https://www.mastercard.com",
    "checked": "28.07.2026",
    "note": "Глобальна платіжна система та технології Рік заснування: 1966.",
    "year": "1966"
  },
  {
    "id": "paypal",
    "name": "PayPal",
    "initials": "P",
    "category": "Електронні платежі",
    "country": "США",
    "countryCode": "US",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "paypal.com",
    "url": "https://www.paypal.com",
    "checked": "28.07.2026",
    "note": "Онлайн-перекази, електронний гаманець Рік заснування: 1998.",
    "year": "1998"
  },
  {
    "id": "lego",
    "name": "Lego",
    "initials": "L",
    "category": "Іграшки / Конструктори",
    "country": "Данія",
    "countryCode": "DK",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "lego.com",
    "url": "https://www.lego.com",
    "checked": "28.07.2026",
    "note": "Пластикові конструктори для дітей та дорослих Рік заснування: 1932.",
    "year": "1932"
  },
  {
    "id": "red-bull",
    "name": "Red Bull",
    "initials": "RB",
    "category": "Енергетичні напої / Спорт",
    "country": "Австрія",
    "countryCode": "AT",
    "type": "Сайт виробника",
    "status": "verified",
    "site": "redbull.com",
    "url": "https://www.redbull.com",
    "checked": "28.07.2026",
    "note": "Офіційний сайт бренду Red Bull.",
    "year": ""
  }
];
